-- +goose Up
-- +goose StatementBegin
CREATE extension if not exists citext; -- provides data type for case insensitive text;
CREATE TABLE USERS (
	id bigint primary key generated by default as identity,
	email citext not null unique
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE USERS;
-- +goose StatementEnd
