server:
  port: 8080
  
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: autograder
  sslmode: disable

auth:
  jwt:
    secret: secret # Change this to a long random string
    access_token_duration: 15m
    refresh_token_duration: 48h
  admins:
  - mharold@udallas.edu
