server:
  port: "8080"
  
db:
  host: ${{ secrets.DB_HOST }}
  port: ${{ secrets.DB_PORT }}
  user: ${{ secrets.DB_USER }}
  password: ${{ secrets.DB_PASS }}
  dbname: ${{ secrets.DB_NAME }}
  sslmode: disable

auth:
  jwt:
    secret: ${{ secrets.JWT_SECRET }}
    access_token_duration: 15m
    refresh_token_duration: 48h
  admins:
  - acm@udallas.edu
  - test@udallas.edu
  - mharold@udallas.edu
