name: Deploy Backend to Firebase

on:
  push:
    branches:
      - live  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build frontend
        working-directory: web
        run: |
          yarn install
          yarn build

      - name: List contents of build output
        run: ls -R

      - name: Deploy Go backend via Cloud Run (no Dockerfile)
        run: |
          gcloud run deploy autograder-backend \
            --source . \
            --region $REGION \
            --project $PROJECT_ID \
            --allow-unauthenticated

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting