name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - live  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Build frontend
        run: |
          cd web
          yarn install
          yarn build

      - name: Build and Test
        run: |
          go mod tidy
          go test ./...

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Run Goose Migrations
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          goose -dir db/migrations postgres "user=${{ secrets.DB_USER }} password=${{ secrets.DB_PASSWORD }} dbname=${{ secrets.DB_NAME }} host=/cloudsql/udcs-autograder:us-central1:autograder-db sslmode=disable" up

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with: 
          service: autograder-api
          region: us-central1
          source: .
          project_id: udcs-autograder
          flags: --add-cloudsql-instances=udcs-autograder:us-central1:autograder-db --timeout=600s --port=8080
          env_vars: |
            DB_HOST=cloudsql
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}