name: Deploy Backend to Firebase

on:
  push:
    branches:
      - live  # or your default branch

env:
  PROJECT_ID: udcs-autograder
  REGION: us-central1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: subdir/go.sum

      - name: Download and install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build frontend
        working-directory: web
        run: |
          yarn install
          yarn build

      - name: List contents of build output
        run: ls -R
      - uses: google-github-actions/auth@v1
        with: 
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UDCS_AUTOGRADER }}'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UDCS_AUTOGRADER }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{env.PROJECT_ID}}
      - name: Pre-creating Artifact Registry Repository
        run:
          gcloud artifacts repositories create cloud-run-source-deploy \
          --repository-format docker \
          --location ${{env.REGION}} \
          --project ${{env.PROJECT_ID}} 
      - name: Deploy Go backend via Cloud Run (no Dockerfile)
        run: |
          gcloud run deploy autograder-backend \
            --source . \
            --region ${{env.REGION}} \
            --project ${{env.PROJECT_ID}} \
            --allow-unauthenticated

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting